### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by 3d0n1** [UBoat-Botnet/UBoat#29]
I have problems with the login page
actually it is captcha does not show captcha text or picture and whatever i try typing it say captcha error :)

**Comment by namedjbour** [comment]
same problem here

**Comment by namedjbour** [comment]
i fixed this with 
adding in 
/private/helpers/capcha.php

after
```
        for ($i = 0; $i < rand(3,5); $i++) {
            $code .= $characters[mt_rand(0, strlen($characters) - 1)];
        }
```

insert like this ==>
```
        for ($i = 0; $i < rand(3,5); $i++) {
            $code .= $characters[mt_rand(0, strlen($characters) - 1)];
        }
	$code = "123456";
```

your capcha will be     **123456**

**Comment by 3d0n1** [comment]
@namedjbour fixed that but there is now errors can't login did u fix that to?

**Comment by matricali** [comment]
In order to captcha works properly you need to have installed and enabled the "gd" extension in your PHP installation.
