### ISSUE TITLE
Problems creating the password hash for the panel user

### ISSUE THREAD

**Issue by khalid2204** [UBoat-Botnet/UBoat#38]
Hello i'm having a problem related to the hash when i open the url i dont see the generated hash
my url is 127.0.0.1/Panel/test.php

**Comment by matricali** [comment]
Hi @ khalid2204, do you see a mistake or something?

**Comment by matricali** [comment]
```
<?php
echo password_hash('<<YOUR PASSWORD GOES HERE>>', DEFAULT_PASSWORD);
```

**Comment by matricali** [comment]
Hi @khalid2204, any feedback on this?
