### ISSUE TITLE
I got this after i login any fix?

### ISSUE THREAD

**Issue by CBBx218** [UBoat-Botnet/UBoat#52]
Warning: PDO::prepare(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uboat.user' doesn't exist in /var/www/src/Model.php on line 42

Fatal error: Uncaught Error: Call to a member function execute() on boolean in /var/www/src/Model.php:46 Stack trace: #0 /var/www/src/models/user.php(11): Model->query('SELECT * FROM `...', Array) #1 /var/www/src/controllers/login.php(32): user->actionAuth(Array) #2 /var/www/src/goat.php(75): Login->index() #3 /var/www/html/index.php(22): goat->__construct(Array) #4 {main} thrown in /var/www/src/Model.php on line 46

**Comment by matricali** [comment]
Duplicated: UBoat-Botnet/UBoat-Panel#4
