### ISSUE TITLE
How to get bots?

### ISSUE THREAD

**Issue by FreezyEx** [UBoat-Botnet/UBoat#55]
From the pics I can't understand how to infect and getting bots

**Comment by matricali** [comment]
The project doesn't provide any infection mechanism.
This project aims to study, analyze and know-how works a botnet (in general).

Of course, it is fully functional if you distribute your executables yourself

**Comment by FreezyEx** [comment]
Ok but how can i make a payload exe

Il Ven 4 Dic 2020, 15:22 Jorge Matricali <notifications@github.com> ha
scritto:
