### ISSUE TITLE
Compile Errors on Windows 10 machine

### ISSUE THREAD

**Issue by whichbuffer** [UBoat-Botnet/UBoat#56]
I'm try to compile UBoat on Visual Sutdio 2019 but I get this error/warning messages

## This one on Debug
![Capture](https://user-images.githubusercontent.com/42712921/100547266-e1c13f00-3276-11eb-8ed5-a017e2da65cd.PNG)

## And this was Release
![Release](https://user-images.githubusercontent.com/42712921/100547267-e1c13f00-3276-11eb-9604-f27919851dd3.png)

## Debug log file:

https://ghostbin.co/paste/fgh9

## Release log file:

https://ghostbin.co/paste/dd59brs

**Comment by Souhardya** [comment]
Change your subsystem or just define main instead of Winmain

**Comment by whichbuffer** [comment]
Yes it's worked ! I just changed Winmain to main

**Comment by Souhardya** [comment]
Please update the startup.cpp file from the current repository a lot of portion is changed and then recompile

**Comment by whichbuffer** [comment]
well now that's worked  :)
