### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by stim555** [UBoat-Botnet/UBoat#58]
when I try to build a project in VS 2019, I get an error. Debugging also fails.
![Screenshot_3](https://user-images.githubusercontent.com/78044377/115169070-b1fbc200-a0c5-11eb-9d29-5383d1e01507.png)

**Comment by Souhardya** [comment]
use _CRT_SECURE_NO_WARNINGS directive in Preprocessor Definitions / https://stackoverflow.com/questions/59378190/windows-sapi-error-getversionexa-was-declared-deprecated / add #include <intrin.h> to resolve cpuid issue

**Comment by Jackson-Pollock** [comment]
In which file to add this? It will be great if you can update code/docs correctly, lot of people are giving up due to no code/doc maintenance.
