### ISSUE TITLE
botnet panel error

### ISSUE THREAD

**Issue by Zaiza777** [UBoat-Botnet/UBoat#59]
![image](https://user-images.githubusercontent.com/58741835/116200043-87061380-a740-11eb-8957-dd2a67ae0b7c.png)

I wrote sudo docker-compose up --build
he gives me an answer like this
But here we have not yet installed the database and have not done anything like this, we have done before
run phpmyadmin separately
Even in the database itself, a user was created, etc., but all the time the same error

I will be very glad for your help.=)

**Comment by matricali** [comment]
Has been fixed on UBoat-Botnet/UBoat-Panel#5
