### ISSUE TITLE
bot build issues, someone please share bot.exe

### ISSUE THREAD

**Issue by Jackson-Pollock** [UBoat-Botnet/UBoat#64]
I am getting lot of errors in vs 22 and build is failing. Please release bot.exe for win10

**Comment by Jackson-Pollock** [comment]
similar to https://github.com/UBoat-Botnet/UBoat/issues/58
![image](https://user-images.githubusercontent.com/62762611/169097179-fafc4e8b-d40a-491a-8f0f-57f33dd6c44b.png)

**Comment by Jackson-Pollock** [comment]
Update;
After lot of efforts I was able to build exe with 0 errors but it is not connecting to external panel (url updated in gate.h) also no Wireshark connections.

**Comment by Jackson-Pollock** [comment]
This will be last update: 
```Exception thrown at 0x00007FF71F6E5433 in boat.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FF71F6E5433 in boat.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Exception thrown at 0x00007FF71F6E5433 in boat.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FF71F6E5433 in boat.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

**Comment by texas-john** [comment]
> Already wasted my time and it didn't worked, giving up finally. developers of this project need to understand either maintain code/docs properly otherwise add disclaimer of **try at your own risk of wasting time**, incase of you guys don't care anything then please delete this project so that no one can waste time.

yeah same I wasted a lot of time with this
