### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by AhmedSakrr** [UBoat-Botnet/UBoat#67]
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\PHP\vendor\model.php:10 Stack trace: #0 C:\xampp\htdocs\PHP\vendor\model.php(10): PDO->__construct('mysql:host=loca...', 'root', Object(SensitiveParameterValue)) #1 C:\xampp\htdocs\PHP\vendor\controller.php(48): Model->__construct() #2 C:\xampp\htdocs\PHP\private\controllers\login.php(30): Controller->loadModel('user') #3 C:\xampp\htdocs\PHP\vendor\goat.php(90): Login->index() #4 C:\xampp\htdocs\PHP\index.php(22): goat->__construct(Array) #5 {main} thrown in C:\xampp\htdocs\PHP\vendor\model.php on line 10

https://imgur.com/a/EOnFxhC

**Comment by matricali** [comment]
You should change the database username and password in the config file (config.php)
https://github.com/UBoat-Botnet/UBoat/wiki/Panel-Setup#31-locate-panelsrcconfigconfigphp
